export enum ErrorEnum {
  GENERAL_ERROR = 'VALIDATE.GENERAL_ERROR',
  SERVER_ERROR = 'VALIDATE.SERVER_ERROR',
  NOT_FOUND = 'VALIDATE.NOT_FOUND',
  BAD_REQUEST = 'VALIDATE.BAD_REQUEST',
  AUTHENTICATION_FAILED = 'VALIDATE.AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED = 'VALIDATE.AUTHORIZATION_FAILED',
}
