version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - export ROLLUP_SKIP_NATIVE=true
      - export VITE_FORCE_ESBUILD=true
      - npm run build:simple || npm run build:pure || npm run build:esbuild || (echo "All builds failed" && exit 1)
  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
