// interest.enum.ts
export enum LeadIntentEnum {
  POSITIVE_INTEREST = 'POSITIVE_INTEREST',
  REQUEST_INFO = 'REQUEST_INFO',
  NEUTRAL = 'NEUTRAL',
  NOT_NOW = 'NOT_NOW',
  DECLINE = 'DECLINE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
  AMBIGUOUS = 'AMBIGUOUS',
  ABUSIVE = 'ABUSIVE',
}

export enum LeadActionEnum {
  REPLY = 'REPLY',
  ASK_CLARIFY = 'ASK_CLARIFY',
  DO_NOT_CONTACT = 'DO_NOT_CONTACT',
  ADD_TO_DNC = 'ADD_TO_DNC',
  SCHEDULE_FOLLOW_UP = 'SCHEDULE_FOLLOW_UP',
}

export enum LeadDepartmentEnum {
  CAR_DEPARTMENT = 'CAR_DEPARTMENT',
  MORTGAGE_DEPARTMENT = 'MORTGAGE_DEPARTMENT',
  LOAN_DEPARTMENT = 'LOAN_DEPARTMENT',
}
