export enum ConversationEventEnum {
  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_CONVERSATION = 'NEW_CONVERSATION',
  MESSAGE_STATUS_UPDATE = 'MESSAGE_STATUS_UPDATE',
  SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE',
  CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
}
