export const statusCodeMap = new Map<number, string>()
  .set(200, 'INSTANCE.STATUS.CONNECTED')
  .set(401, 'INSTANCE.STATUS.LOGGED_OUT')
  .set(403, 'INSTANCE.STATUS.BLOCKED')
  .set(408, 'INSTANCE.STATUS.REGISTRATION_INCOMPLETED');
