export enum RecordValidatorMessage {
  GENERAL_ERROR = 'VALIDATE.GENERAL_ERROR',
  INVALID_TYPE = 'VALIDATE.INVALID_TYPE',
  MAX = 'VALIDATE.MAX',
  MIN = 'VALIDATE.MIN',
  LENGTH = 'VALIDATE.LENGTH',
  MAX_LENGTH = 'VALIDATE.MAX_LENGTH',
  MIN_LENGTH = 'VALIDATE.MIN_LENGTH',
  MISMATCH = 'VALIDATE.MISMATCH',
  REQUIRED = 'VALIDATE.REQUIRED',
}
