export enum InstanceEventEnum {
  INSTANCE_UPDATE = 'INSTANCE_UPDATE',
  INSTANCE_WARM_END = 'INSTANCE_WARM_END',
  INSTANCE_WARM_START = 'INSTANCE_WARM_START',
  INSTANCE_NEXT_WARM_AT = 'INSTANCE_NEXT_WARM_AT',
  INSTANCE_REGISTERED = 'INSTANCE_REGISTERED',
}
