export enum MessageQueueEventEnum {
  QUEUE_SEND_ACTIVATED = 'QUEUE_SEND_ACTIVATED',
  QUEUE_SEND_COMPLETED = 'QUEUE_SEND_COMPLETED',
  QUEUE_MESSAGE_SENT = 'QUEUE_MESSAGE_SENT',
  QUEUE_MESSAGE_FAILED = 'QUEUE_MESSAGE_FAILED',
}
