export enum MessageQueueEventEnum {
  QUEUE_SEND_ACTIVATED = 'QUEUE_SEND_ACTIVATED',
  QUEUE_SEND_DEACTIVATED = 'QUEUE_SEND_DEACTIVATED',
  QUEUE_MESSAGE_SENT = 'QUEUE_MESSAGE_SENT',
  QUEUE_MESSAGE_FAILED = 'QUEUE_MESSAGE_FAILED',
}
